name: Concurrency
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # this workflow and this branch
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: sleep 30
