name: Parallel
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello World, I am from step 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo "Hello World, I am from step 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: echo "Hello World, I am from step 3"